# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        ROLE_CLIENT:      ROLE_USER
        ROLE_OUVRIER:     ROLE_USER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
               
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                use_forward: false
                always_use_default_target_path: false

            logout:
                target: /
            anonymous:    true

    access_control:

        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/boutique/admin/, role: ROLE_ADMIN }
        - { path: ^/client/, role: ROLE_CLIENT }
        - { path: ^/ajouterOuvrier/, role: ROLE_OUVRIER }
