<?php

namespace BoutiqueBundle\Repository;

use BoutiqueBundle\Entity\Categorie;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function triarticle(){
        $p=$this->getEntityManager()->createQuery("SELECT e FROM BoutiqueBundle:Article e ORDER BY e.dateCreationArticle DESC");
        return $p->getResult();}

    public function findNumberOfPostsByCategory($category){
        $qb = $this->getEntityManager()
            ->createQuery("SELECT COUNT(a) as number from BoutiqueBundle:Article a WHERE a.category =:cat ")
            ->setParameters(array('cat' => $category));
        return($qb->getSingleResult());
    }

    public  function bestevents(){
        return $this->getEntityManager()
            ->createQuery("SELECT sum(n.nombreNote)/count(n.id) as note , e.nomArticle as nom  FROM BoutiqueBundle:Article e left join BoutiqueBundle:Note n with n.noteart= e GROUP by n.noteart  order by note desc ")->setMaxResults(5)->getResult();    }
}
