<?php

namespace BoutiqueBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
    public function findP($recherche)
  {
    $q=$this->getEntityManager()->createQuery("select p from BoutiqueBundle:Produit p where p.libelle Like
         :recherche OR p.prix Like :recherche")->setParameter('recherche','%'.$recherche.'%');
    return $q->getResult();
  }
}
