<?php

namespace BoutiqueBundle\Repository;

/**
 * RatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingRepository extends \Doctrine\ORM\EntityRepository
{
    public function getRate($produit)
  {
    $q=$this->getEntityManager()->createQuery("select SUM(c.rating) from 
         BoutiqueBundle:Rating c where c.produit Like :produit")->setParameter('produit','%'.$produit.'%');
    return $q->getResult();
  }
    public function getverif($user,$produit)
    {
        $q=$this->getEntityManager()->createQuery("select c from 
         BoutiqueBundle:Rating c where c.user Like :user AND c.produit Like :produit")->setParameter('user','%'.$user.'%')->setParameter('produit','%'.$produit.'%');
        return $q->getResult();
    }
    public function getNum($produit)
    {
        $q=$this->getEntityManager()->createQuery("select count(c.produit) from 
         BoutiqueBundle:Rating c where c.produit Like :produit")->setParameter('produit','%'.$produit.'%');
        return $q->getResult();
    }
}
